export const ALL_BOOK_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_BOOK_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_BOOK_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_BOOK_REQUEST = "ADMIN_BOOK_REQUEST";
export const ADMIN_BOOK_SUCCESS = "ADMIN_BOOK_SUCCESS";
export const ADMIN_BOOK_FAIL = "ADMIN_BOOK_FAIL";



export const NEW_BOOK_REQUEST = "NEW_BOOK_REQUEST";
export const NEW_BOOK_SUCCESS = "NEW_BOOK_SUCCESS";
export const NEW_BOOK_FAIL = "NEW_BOOK_FAIL";
export const NEW_BOOK_RESET = "NEW_BOOK_RESET";




export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";
export const DELETE_BOOK_RESET = "DELETE_BOOK_RESET";




export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";





export const BORROW_BOOK_REQUEST = "BORROW_BOOK_REQUEST";
export const BORROW_BOOK_SUCCESS = "BORROW_BOOK_SUCCESS";
export const BORROW_BOOK_FAIL = "BORROW_BOOK_FAIL";




export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAIL = "GET_BOOK_FAIL";



export const GET_BOOK_ADMIN_REQUEST = "GET_BOOK_ADMIN_REQUEST";
export const GET_BOOK_ADMIN_SUCCESS = "GET_BOOK_ADMIN_SUCCESS";
export const GET_BOOK_ADMIN_FAIL = "GET_BOOK_ADMIN_FAIL";



export const LIBRARY_TRANSACTION_REQUEST = "LIBRARY_TRANSACTION_REQUEST";
export const LIBRARY_TRANSACTION_SUCCESS = "LIBRARY_TRANSACTION_SUCCESS";
export const LIBRARY_TRANSACTION_FAIL = "LIBRARY_TRANSACTION_FAIL";



export const ACCEPT_RETURN_REQUEST = "ACCEPT_RETURN_REQUEST";
export const ACCEPT_RETURN_SUCCESS = "ACCEPT_RETURN_SUCCESS";
export const ACCEPT_RETURN_RESET = "ACCEPT_RETURN_RESET";
export const ACCEPT_RETURN_FAIL = "ACCEPT_RETURN_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";