export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_LOGIN_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER__FAIL";



export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";


export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET= "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";


export const RETURN_USER_REQUEST = "RETURN_USER_REQUEST";
export const RETURN_USER_SUCCESS = "RETURN_USER_SUCCESS";
export const RETURN_USER_RESET= "RETURN_USER_RESET";
export const RETURN_USER_FAIL = "RETURN_USER_FAIL";

export const ADMIN_RETURN_BOOK_REQUEST = "ADMIN_RETURN_BOOK_REQUEST";
export const ADMIN_RETURN_BOOK_SUCCESS = "ADMIN_RETURN_BOOK_SUCCESS";
export const ADMIN_RETURN_BOOK_RESET= "ADMIN_RETURN_BOOK_RESET";
export const ADMIN_RETURN_BOOK_FAIL = "ADMIN_RETURN_BOOK_FAIL";





export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";




export const CLEAR_ERRORS = "CLEAR_ERRORS";